@baseUrl = https://api.themoviedb.org/3
@apiKey = fa0a7c3829770be03e723f3d1b5fd96a

GET {{baseUrl}}/movie/upcoming?api_key={{apiKey}}&page=1

###

GET {{baseUrl}}/movie/580489?api_key={{apiKey}}
If-None-Match: W/"6f7b79d8b887706b68099374a25617df"

